// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUPB4xIl02d0J7x22s9DSiGCEmVf1YuZk',
    appId: '1:823385659199:web:f67416eaf699ddb867e58a',
    messagingSenderId: '823385659199',
    projectId: 'tiny-gym-flutter',
    authDomain: 'tiny-gym-flutter.firebaseapp.com',
    storageBucket: 'tiny-gym-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2GdqG_q0Kvv2EDGpXWjVnQqCTh4cGLt0',
    appId: '1:823385659199:android:5805f992b92ec6b067e58a',
    messagingSenderId: '823385659199',
    projectId: 'tiny-gym-flutter',
    storageBucket: 'tiny-gym-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChpCjP4NcnHdHyPurD2-et3XAEv6mYPlc',
    appId: '1:823385659199:ios:9fee659caa67d55767e58a',
    messagingSenderId: '823385659199',
    projectId: 'tiny-gym-flutter',
    storageBucket: 'tiny-gym-flutter.appspot.com',
    iosClientId: '823385659199-d6lo5qu7edhrsjl86vslvnh2sjp7hg97.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniWorkoutManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChpCjP4NcnHdHyPurD2-et3XAEv6mYPlc',
    appId: '1:823385659199:ios:9fee659caa67d55767e58a',
    messagingSenderId: '823385659199',
    projectId: 'tiny-gym-flutter',
    storageBucket: 'tiny-gym-flutter.appspot.com',
    iosClientId: '823385659199-d6lo5qu7edhrsjl86vslvnh2sjp7hg97.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniWorkoutManager',
  );
}
